# Analysis of Forced Isotropic Flow

In [1]:
% pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
import pandas as pd
import pyJHTDB

In [3]:
b = np.zeros( 65, dtype=int )
for i in range(65):
    b[i] = i/64*(512**3)
    print(b[i])

0
2097152
4194304
6291456
8388608
10485760
12582912
14680064
16777216
18874368
20971520
23068672
25165824
27262976
29360128
31457280
33554432
35651584
37748736
39845888
41943040
44040192
46137344
48234496
50331648
52428800
54525952
56623104
58720256
60817408
62914560
65011712
67108864
69206016
71303168
73400320
75497472
77594624
79691776
81788928
83886080
85983232
88080384
90177536
92274688
94371840
96468992
98566144
100663296
102760448
104857600
106954752
109051904
111149056
113246208
115343360
117440512
119537664
121634816
123731968
125829120
127926272
130023424
132120576
134217728


In [4]:
for i in range(64):
    print(b[i], b[i+1])

0 2097152
2097152 4194304
4194304 6291456
6291456 8388608
8388608 10485760
10485760 12582912
12582912 14680064
14680064 16777216
16777216 18874368
18874368 20971520
20971520 23068672
23068672 25165824
25165824 27262976
27262976 29360128
29360128 31457280
31457280 33554432
33554432 35651584
35651584 37748736
37748736 39845888
39845888 41943040
41943040 44040192
44040192 46137344
46137344 48234496
48234496 50331648
50331648 52428800
52428800 54525952
54525952 56623104
56623104 58720256
58720256 60817408
60817408 62914560
62914560 65011712
65011712 67108864
67108864 69206016
69206016 71303168
71303168 73400320
73400320 75497472
75497472 77594624
77594624 79691776
79691776 81788928
81788928 83886080
83886080 85983232
85983232 88080384
88080384 90177536
90177536 92274688
92274688 94371840
94371840 96468992
96468992 98566144
98566144 100663296
100663296 102760448
102760448 104857600
104857600 106954752
106954752 109051904
109051904 111149056
111149056 113246208
113246208 115343360
115343360 

In [5]:
134217728 / 64

2097152.0

### High-resolution snapshot

In [6]:
data = pyJHTDB.dbinfo.isotropic1024coarse
data

{'name': 'isotropic1024coarse',
 'xnodes': array([0.0000000e+00, 6.1359233e-03, 1.2271847e-02, ..., 6.2647777e+00,
        6.2709136e+00, 6.2770495e+00], dtype=float32),
 'nx': 1024,
 'lx': 6.283185307179586,
 'dx': 0.006135923151542565,
 'xperiodic': True,
 'xuniform': True,
 'ynodes': array([0.0000000e+00, 6.1359233e-03, 1.2271847e-02, ..., 6.2647777e+00,
        6.2709136e+00, 6.2770495e+00], dtype=float32),
 'ny': 1024,
 'ly': 6.283185307179586,
 'dy': 0.006135923151542565,
 'yperiodic': True,
 'yuniform': True,
 'znodes': array([0.0000000e+00, 6.1359233e-03, 1.2271847e-02, ..., 6.2647777e+00,
        6.2709136e+00, 6.2770495e+00], dtype=float32),
 'nz': 1024,
 'lz': 6.283185307179586,
 'dz': 0.006135923151542565,
 'zperiodic': True,
 'zuniform': True,
 'time': array([0.0000000e+00, 1.9999999e-03, 3.9999997e-03, ..., 1.0049999e+01,
        1.0051999e+01, 1.0054000e+01], dtype=float32),
 'diss': 0.0928,
 'nu': 0.000185}

In [7]:
# nu = data['nu']

In [8]:
L = 512
xnodes = data['xnodes'][:L]
ynodes = data['ynodes'][:L]
znodes = data['znodes'][:L]

In [9]:
import itertools

In [10]:
%%time
# getting all possible coordinate points
points = np.array(list(itertools.product(xnodes, ynodes, znodes ) ) ) 

CPU times: user 2min 31s, sys: 44.6 s, total: 3min 16s
Wall time: 3min 12s


In [11]:
points.shape

(134217728, 3)

In [12]:
points[:5]

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.00613592],
       [0.        , 0.        , 0.01227185],
       [0.        , 0.        , 0.01840777],
       [0.        , 0.        , 0.02454369]], dtype=float32)

In [13]:
points[::256][:5] #print with ny steps

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.5707964 ],
       [0.        , 0.00613592, 0.        ],
       [0.        , 0.00613592, 1.5707964 ],
       [0.        , 0.01227185, 0.        ]], dtype=float32)

In [14]:
points[::256*256][:5]

array([[0.        , 0.        , 0.        ],
       [0.        , 0.7853982 , 0.        ],
       [0.        , 1.5707964 , 0.        ],
       [0.        , 2.3561945 , 0.        ],
       [0.00613592, 0.        , 0.        ]], dtype=float32)

### Requesting velocity

In [15]:
# load shared library
lTDB = pyJHTDB.libJHTDB()

# initialize webservices
lTDB.initialize()

# add token
auth_token  = "hu.elte.caesar.abiricz-fe734327"
lTDB.add_token(auth_token)

N = points.shape
print('First few coordinates of {0} points where variables are requested:'.format(N))
for p in range(10):
    print('{0}: {1}'.format(p, points[p]))

First few coordinates of (134217728, 3) points where variables are requested:
0: [0. 0. 0.]
1: [0.         0.         0.00613592]
2: [0.         0.         0.01227185]
3: [0.         0.         0.01840777]
4: [0.         0.         0.02454369]
5: [0.         0.         0.03067962]
6: [0.         0.         0.03681554]
7: [0.         0.         0.04295146]
8: [0.         0.         0.04908739]
9: [0.         0.         0.05522331]


In [16]:
%%time
for i in range(64)[25:]: # MODIFY HERE IF FAILURE OCCURS
    print('Requesting velocity at {0} points...'.format(N))
    vel_at_points = lTDB.getData( 0, points[ b[i]:b[i+1] ], 
                                 data_set = 'isotropic1024coarse', getFunction = 'Velocity' )
    for p in range(3):
        print(i, '. turn')
        print('{0}: {1}'.format(p, vel_at_points[p]))
    #constructing a DataFrame to join the corresponding data
    Data = pd.DataFrame( points[ b[i]:b[i+1] ], columns = ['x', 'y', 'z'] )
    Data['v_x'] = vel_at_points[:,0]
    Data['v_y'] = vel_at_points[:,1]
    Data['v_z'] = vel_at_points[:,2]
    
    FD4Lag4 = 44
    temporalInterp = 0

    print('Requesting velocity gradient at {0} points...'.format(N))
    vel_grad_at_points = lTDB.getData( 0, points[ b[i]:b[i+1] ], sinterp = FD4Lag4, 
                                      tinterp = temporalInterp, data_set ='isotropic1024coarse', 
                                      getFunction = 'getVelocityGradient')
    for p in range(3):
        print(i, '. turn')
        print('{0}: '.format(p) +
              'duxdx = {0:+e}, duxdy = {1:+e}, duxdz = {2:+e}\n   '.format(vel_grad_at_points[p][0], vel_grad_at_points[p][1], vel_grad_at_points[p][2]) +
              'duydx = {0:+e}, duydy = {1:+e}, duydz = {2:+e}\n   '.format(vel_grad_at_points[p][3], vel_grad_at_points[p][4], vel_grad_at_points[p][5]) +
              'duzdx = {0:+e}, duzdy = {1:+e}, duzdz = {2:+e}'.format(vel_grad_at_points[p][6], vel_grad_at_points[p][7], vel_grad_at_points[p][8]))
    
    #constructing a DataFrame to join the corresponding data
    Data['d_ux_dx'] = vel_grad_at_points[:,0]
    Data['d_ux_dy'] = vel_grad_at_points[:,1]
    Data['d_ux_dz'] = vel_grad_at_points[:,2]
    Data['d_uy_dx'] = vel_grad_at_points[:,3]
    Data['d_uy_dy'] = vel_grad_at_points[:,4]
    Data['d_uy_dz'] = vel_grad_at_points[:,5]
    Data['d_uz_dx'] = vel_grad_at_points[:,6]
    Data['d_uz_dy'] = vel_grad_at_points[:,7]
    Data['d_uz_dz'] = vel_grad_at_points[:,8]
    
    Data.to_csv( "~/workspace/Temporary/abiricz/scratch/Isoturb_box512_"+str(i)+".csv", index=False, header=False )

Requesting velocity at (134217728, 3) points...
25 . turn
0: [ 0.9052996 -0.2406579 -0.7347213]
25 . turn
1: [ 0.9066962  -0.25275964 -0.72218347]
25 . turn
2: [ 0.9039475 -0.264122  -0.7451576]
Requesting velocity gradient at (134217728, 3) points...
25 . turn
0: duxdx = +4.415143e+00, duxdy = +2.733772e+00, duxdz = -3.906021e-01
   duydx = -3.293556e-01, duydy = -7.733021e+00, duydz = -6.963921e-01
   duzdx = -2.917552e-02, duzdy = -8.342728e+00, duzdz = +3.670952e+00
25 . turn
1: duxdx = +5.551190e+00, duxdy = +5.823669e-01, duxdz = +1.463184e-01
   duydx = -2.799181e+00, duydy = -4.997108e+00, duydz = -2.410482e+00
   duzdx = -1.918075e-01, duzdy = -1.406956e+01, duzdz = -4.680347e-01
25 . turn
2: duxdx = +6.014963e+00, duxdy = -3.403915e+00, duxdz = -1.298426e+00
   duydx = -3.443258e+00, duydy = +1.258669e+00, duydz = -2.504959e-01
   duzdx = -1.703180e+00, duzdy = -2.093524e+01, duzdz = -7.608333e+00
Requesting velocity at (134217728, 3) points...
26 . turn
0: [ 1.2239206  -0.54

Requesting velocity at (134217728, 3) points...
34 . turn
0: [ 0.9254978  -0.44329208 -0.47715357]
34 . turn
1: [ 0.9087258  -0.33977222 -0.46069354]
34 . turn
2: [ 0.87976813 -0.2715586  -0.42513278]
Requesting velocity gradient at (134217728, 3) points...
34 . turn
0: duxdx = -5.257727e+00, duxdy = -4.557419e+00, duxdz = -2.573448e+00
   duydx = +7.785674e+00, duydy = +4.994133e+00, duydz = +2.097597e+01
   duzdx = -2.929244e+00, duzdy = -1.058524e+01, duzdz = +3.960495e-01
34 . turn
1: duxdx = -8.344100e+00, duxdy = -3.874908e+00, duxdz = -3.592131e+00
   duydx = +2.901298e+00, duydy = +3.606735e+00, duydz = +1.382392e+01
   duzdx = -2.216095e+00, duzdy = -1.055823e+01, duzdz = +4.575732e+00
34 . turn
2: duxdx = -8.837213e+00, duxdy = -9.567337e-01, duxdz = -5.739915e+00
   duydx = -1.721370e-01, duydy = +2.556152e+00, duydz = +9.158647e+00
   duzdx = -1.350116e+00, duzdy = -9.973587e+00, duzdz = +6.366417e+00
Requesting velocity at (134217728, 3) points...
35 . turn
0: [ 0.7079709 

Requesting velocity at (134217728, 3) points...
43 . turn
0: [ 0.6210479   0.26555353 -1.2535634 ]
43 . turn
1: [ 0.6196016   0.28992534 -1.2503611 ]
43 . turn
2: [ 0.6197602   0.31330797 -1.2432072 ]
Requesting velocity gradient at (134217728, 3) points...
43 . turn
0: duxdx = -7.252179e-02, duxdy = -5.150711e+00, duxdz = -6.924171e-01
   duydx = +3.732224e+00, duydy = -9.508133e-03, duydz = +3.998255e+00
   duzdx = -2.962833e+00, duzdy = -4.690697e+00, duzdz = +2.378082e-02
43 . turn
1: duxdx = +9.191424e-01, duxdy = -5.513184e+00, duxdz = -5.084610e-02
   duydx = +4.180210e+00, duydy = -1.838806e+00, duydz = +3.952369e+00
   duzdx = -3.111910e+00, duzdy = -4.975647e+00, duzdz = +8.585663e-01
43 . turn
2: duxdx = +1.562393e+00, duxdy = -6.344978e+00, duxdz = +1.298926e-01
   duydx = +4.321607e+00, duydy = -3.109884e+00, duydz = +3.587915e+00
   duzdx = -3.158771e+00, duzdy = -4.997742e+00, duzdz = +1.599060e+00
Requesting velocity at (134217728, 3) points...
44 . turn
0: [ 0.82586855

Requesting velocity at (134217728, 3) points...
52 . turn
0: [ 0.9197844   0.9319035  -0.13165069]
52 . turn
1: [ 0.9053871   0.9305352  -0.13452005]
52 . turn
2: [ 0.88995063  0.9299738  -0.13927028]
Requesting velocity gradient at (134217728, 3) points...
52 . turn
0: duxdx = +1.282087e+00, duxdy = +1.092163e+00, duxdz = -1.814697e+00
   duydx = +7.950327e-01, duydy = -1.073883e+00, duydz = -6.277466e-01
   duzdx = +7.816579e-02, duzdy = -8.093681e-01, duzdz = -2.046556e-01
52 . turn
1: duxdx = +1.054191e+00, duxdy = +6.117859e-01, duxdz = -2.524871e+00
   duydx = +6.157852e-01, duydy = -2.794189e-01, duydz = -2.045269e-01
   duzdx = +2.940796e-01, duzdy = -1.035582e+00, duzdz = -7.020614e-01
52 . turn
2: duxdx = +5.921044e-01, duxdy = +5.815659e-01, duxdz = -2.354401e+00
   duydx = +2.827693e-01, duydy = +2.704620e-02, duydz = +4.581881e-01
   duzdx = +1.454455e-01, duzdy = -8.698549e-01, duzdz = -5.996616e-01
Requesting velocity at (134217728, 3) points...
53 . turn
0: [ 0.9349239 

Requesting velocity at (134217728, 3) points...
61 . turn
0: [ 0.8321918  1.4540793 -0.3622179]
61 . turn
1: [ 0.9142659   1.4244673  -0.36667734]
61 . turn
2: [ 0.9565602   1.4009247  -0.39375174]
Requesting velocity gradient at (134217728, 3) points...
61 . turn
0: duxdx = +2.529460e+00, duxdy = +7.982887e+00, duxdz = +1.271922e+01
   duydx = +1.329030e+00, duydy = -2.342148e+00, duydz = -5.459290e+00
   duzdx = +4.731559e+00, duzdy = -2.095119e+00, duzdz = -2.935677e-01
61 . turn
1: duxdx = +1.666241e+00, duxdy = +7.563019e+00, duxdz = +1.151738e+01
   duydx = +3.805900e-01, duydy = +1.426239e-01, duydz = -4.118288e+00
   duzdx = +4.265351e+00, duzdy = -2.207909e+00, duzdz = -2.361952e+00
61 . turn
2: duxdx = +4.577079e+00, duxdy = -2.420082e+00, duxdz = -3.333888e-01
   duydx = +7.662901e-02, duydy = +1.550720e+00, duydz = -4.294668e+00
   duzdx = +5.111966e+00, duzdy = -3.527958e+00, duzdz = -5.983564e+00
Requesting velocity at (134217728, 3) points...
62 . turn
0: [ 0.8954847   1

In [17]:
# Data.to_csv( 'Isoturb_coords_vels_box128.csv', index=False )

In [18]:
"""%%time
FD4Lag4 = 44
temporalInterp = 0

print('Requesting velocity gradient at {0} points...'.format(N))
vel_grad_at_points = lTDB.getData( 0, points[ b[i]:b[i+1] ], sinterp = FD4Lag4, tinterp = temporalInterp, data_set ='isotropic1024coarse', 
                                  getFunction = 'getVelocityGradient')

for p in range(3):
    print('{0}: '.format(p) +
          'duxdx = {0:+e}, duxdy = {1:+e}, duxdz = {2:+e}\n   '.format(vel_grad_at_points[p][0], vel_grad_at_points[p][1], vel_grad_at_points[p][2]) +
          'duydx = {0:+e}, duydy = {1:+e}, duydz = {2:+e}\n   '.format(vel_grad_at_points[p][3], vel_grad_at_points[p][4], vel_grad_at_points[p][5]) +
          'duzdx = {0:+e}, duzdy = {1:+e}, duzdz = {2:+e}'.format(vel_grad_at_points[p][6], vel_grad_at_points[p][7], vel_grad_at_points[p][8]))"""

"%%time\nFD4Lag4 = 44\ntemporalInterp = 0\n\nprint('Requesting velocity gradient at {0} points...'.format(N))\nvel_grad_at_points = lTDB.getData( 0, points[ b[i]:b[i+1] ], sinterp = FD4Lag4, tinterp = temporalInterp, data_set ='isotropic1024coarse', \n                                  getFunction = 'getVelocityGradient')\n\nfor p in range(3):\n    print('{0}: '.format(p) +\n          'duxdx = {0:+e}, duxdy = {1:+e}, duxdz = {2:+e}\n   '.format(vel_grad_at_points[p][0], vel_grad_at_points[p][1], vel_grad_at_points[p][2]) +\n          'duydx = {0:+e}, duydy = {1:+e}, duydz = {2:+e}\n   '.format(vel_grad_at_points[p][3], vel_grad_at_points[p][4], vel_grad_at_points[p][5]) +\n          'duzdx = {0:+e}, duzdy = {1:+e}, duzdz = {2:+e}'.format(vel_grad_at_points[p][6], vel_grad_at_points[p][7], vel_grad_at_points[p][8]))"

In [19]:
"""Data['d_ux_dx'] = vel_grad_at_points[:,0]
Data['d_ux_dy'] = vel_grad_at_points[:,1]
Data['d_ux_dz'] = vel_grad_at_points[:,2]
Data['d_uy_dx'] = vel_grad_at_points[:,3]
Data['d_uy_dy'] = vel_grad_at_points[:,4]
Data['d_uy_dz'] = vel_grad_at_points[:,5]
Data['d_uz_dx'] = vel_grad_at_points[:,6]
Data['d_uz_dy'] = vel_grad_at_points[:,7]
Data['d_uz_dz'] = vel_grad_at_points[:,8]
#Data.head()"""

"Data['d_ux_dx'] = vel_grad_at_points[:,0]\nData['d_ux_dy'] = vel_grad_at_points[:,1]\nData['d_ux_dz'] = vel_grad_at_points[:,2]\nData['d_uy_dx'] = vel_grad_at_points[:,3]\nData['d_uy_dy'] = vel_grad_at_points[:,4]\nData['d_uy_dz'] = vel_grad_at_points[:,5]\nData['d_uz_dx'] = vel_grad_at_points[:,6]\nData['d_uz_dy'] = vel_grad_at_points[:,7]\nData['d_uz_dz'] = vel_grad_at_points[:,8]\n#Data.head()"

In [20]:
i

63

In [21]:
# Data.to_csv( "Isoturb_box128_"+str(i)+".csv", index=False )